### ISSUE TITLE
Using kfac inside jitted function

### ISSUE THREAD

**Issue by Honza9723** [google-deepmind/kfac-jax#103]
Dear All,

in the problem I am working on, I would need to use Optimizer.step inside a broader function that is jitted for performance reasons. Is there some canonical way, how to do this without dramatically hurting performance and/or inducing some error?

Best,
Honza

**Comment by botev** [comment]
Sorry for the late reply, unfortunately this doesn't send me emails. 
As long as you know what you are doing, you can use kfac inside a `jit` or `pmap` context in the following way:
```
with optimizer.staging_context():
  optimizer._step(...)
```
Note that you will need to call the internal `_step` method instead and to precompute anything that is done in the usual `.step`

**Comment by botev** [comment]
Closing this now.
