### ISSUE TITLE
Value functions returning state objects not supported

### ISSUE THREAD

**Issue by rmclarke** [google-deepmind/kfac-jax#131]
Hi - thank you for the great project!

I'm working with models which carry an internal state, so their forward pass functions return an extra state object. This causes a crash from KFAC-JAX, because that state object is only accounted for at the input, rather than the output.

In `optimizer.convert_value_and_grad_to_value_func`, the flag `has_aux` is used to decide whether to return the value function's output directly or take its index-0 element. As the docstring says, this is similar behaviour to `jax.grad()`, but the flag really refers to _any_ extra output given by the value function, not just an `aux` dictionary. This hits a snag where the function is called in the `Optimizer` constructor (`optimizer.py` line 358), because only `value_func_has_aux` is considered, so `value_func_has_state` doesn't cause the index-0 behaviour like I think it should.

I've fixed this locally by changing that call to use `has_aux=value_func_has_aux or value_func_has_state` - I haven't come across any other problems with state outputs, but I guess they might still exist. This is the patch file I use for the 0.0.3 release:
[kfac_jax.txt](https://github.com/deepmind/kfac-jax/files/11517529/kfac_jax.txt) - I can submit it as a PR if that's helpful.

**Comment by rmclarke** [comment]
To clarify: I do pass this state object into and out of the model. My issue is that I think setting `value_func_has_state = True` should mean we expect a state to get passed in and out, but that flag currently isn't enough to make the optimiser expect a state at the output.

**Comment by botev** [comment]
Could you give an example code for this, so I can understand it fully.

**Comment by rmclarke** [comment]
Of course - here's a MWE:
```python
import jax
import jax.numpy as jnp
import kfac_jax

# A model function which takes and returns a model_state
def model_forward_pass(params, model_state, batch):
    output = params + batch[0] + model_state
    kfac_jax.register_squared_error_loss(output, batch[1])
    return jnp.sum((output - batch[1])**2), model_state

optimiser = kfac_jax.Optimizer(
    value_and_grad_func=jax.value_and_grad(model_forward_pass, has_aux=True),
    value_func_has_state=True,
    value_func_has_aux=False,
    value_func_has_rng=False,
    l2_reg=0,
    use_adaptive_learning_rate=True,
    use_adaptive_momentum=True,
    use_adaptive_damping=True,
    initial_damping=1.0,
    multi_device=False)

data_iterator = (
    (5*jnp.ones((10, 10)), 5*jnp.ones((10, 10)))
    for _ in range(100))

model_params = 2*jnp.ones((10, 10))
model_state = 3*jnp.ones((10, 10))
optimiser_state = optimiser.init(
    model_params,
    jax.random.PRNGKey(123),
    batch=next(data_iterator),
    func_state=model_state)

(new_model_params,
 new_optimiser_state,
 new_model_state,
 statistics) = optimiser.step(
     params=model_params,
     state=optimiser_state,
     func_state=model_state,
     data_iterator=data_iterator,
     rng=jax.random.PRNGKey(123),
     global_step_int=0)
```

This gives me the traceback (skipping JAX internal frames):
```
Traceback (most recent call last):
  File "<cut>/script.py", line 38, in <module>
    statistics) = optimiser.step(
                  ^^^^^^^^^^^^^^^
  File "<cut>/.venv/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 1120, in step
    return self._step(params, state, rng, batch, func_state,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<cut>/.venv/lib/python3.11/site-packages/kfac_jax/_src/utils/staging.py", line 244, in decorated
    outs = jitted_func(instance, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<cut>/.venv/lib/python3.11/site-packages/kfac_jax/_src/utils/misc.py", line 285, in wrapped
    return method(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<cut>/.venv/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 981, in _step
    state.damping, rho, new_loss = lax.cond(
                                   ^^^^^^^^^
  File "<cut>/.venv/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 983, in <lambda>
    lambda args: self._update_damping(*args),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<cut>/.venv/lib/python3.11/site-packages/kfac_jax/_src/utils/misc.py", line 285, in wrapped
    return method(instance, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<cut>/.venv/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 780, in _update_damping
    damping, rho = self._compute_new_damping_and_rho(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<cut>/.venv/lib/python3.11/site-packages/kfac_jax/_src/utils/staging.py", line 192, in decorated
    return method(instance, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "<cut>/.venv/lib/python3.11/site-packages/kfac_jax/_src/optimizer.py", line 1323, in _compute_new_damping_and_rho
    rho = (new_loss - old_loss) / quad_change
           ~~~~~~~~~^~~~~~~~~~
  File "<cut>/.venv/lib/python3.11/site-packages/jax/_src/numpy/array_methods.py", line 723, in op
    return getattr(self.aval, f"_{name}")(self, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<cut>/.venv/lib/python3.11/site-packages/jax/_src/numpy/array_methods.py", line 258, in deferring_binary_op
    raise TypeError(f"unsupported operand type(s) for {opchar}: "
TypeError: unsupported operand type(s) for -: 'tuple' and 'DynamicJaxprTracer'
```

At this point, `new_loss` is precisely the output of `model_forward_pass` - a tuple of loss and model state - but `old_loss` is just a scalar value. I think the model state should be stripped out by `Optimizer.convert_value_and_grad_to_value_func()`, but it's only looking for `aux` data, not model states (see [`_src/optimizer.py` line 387](https://github.com/google-deepmind/kfac-jax/blob/e674c36b05bb6838ce623967ab7f0df835c4048f/kfac_jax/_src/optimizer.py#L387C34-L387C34)).

The code runs without errors if I patch that line as described above.
