### ISSUE TITLE
division by zero error for scalar params

### ISSUE THREAD

**Issue by szbernat** [google-deepmind/kfac-jax#142]
There is a failing edge case in `regular_inverse` within `pi_adjusted_kronecker_inverse`: if there are no non-scalars in `arrays` (`non_scalars==0`) , one cannot [distribute the damping between the non-scalars](https://github.com/deepmind/kfac-jax/blob/f46caed97f6b518b12ec82881530b5057979d423/kfac_jax/_src/utils/math.py#L495) (`1/non_scalars` results in division by zero). This happens e.g. for parameter arrays with size 1.

Since the distributed damping is only needed for non-scalars, one could compute it only in this case.

See https://github.com/MScherbela/kfac-jax/commit/377b4a1735e6e9238ccf1624fde3c4a2d4178387 for a potential fix.

**Comment by botev** [comment]
This is fixed now.
